"""Add nullable full_name to CompanyProfile

Revision ID: 28654bf93cec
Revises: c48248c8476e
Create Date: 2025-07-15 23:38:14.406308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28654bf93cec'
down_revision = 'c48248c8476e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
