"""Initial migration

Revision ID: 4bb02db43dcf
Revises: 
Create Date: 2025-07-07 00:59:38.098900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb02db43dcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_token_serial'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_logged_in', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_user_role'))

    with op.batch_alter_table('vehicle_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_vehicle_log_token_serial'))
        batch_op.create_foreign_key(None, 'users', ['officer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_vehicle_log_token_serial'), ['token_serial'], unique=False)
        batch_op.drop_column('officer_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_role'), ['role'], unique=False)
        batch_op.drop_column('is_logged_in')
        batch_op.drop_column('last_login')

    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_token_serial'), ['serial'], unique=False)

    # ### end Alembic commands ###
