"""Make username non-unique, company_name unique

Revision ID: 890b9f9ce4d3
Revises: f2c101e3cb0e
Create Date: 2025-07-13 19:36:42.839872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890b9f9ce4d3'
down_revision = 'f2c101e3cb0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nrc',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nrc',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
