"""Update User model fields

Revision ID: a4b8012a82ee
Revises: 890b9f9ce4d3
Create Date: 2025-07-13 21:59:26.596084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b8012a82ee'
down_revision = '890b9f9ce4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['company_name'])
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
